export const SEEDED_COURSES = [
  {
    _id: 'c101',
    title: 'Algorithmic Trading & High-Frequency Strategies',
    slug: 'algorithmic-trading-hft-strategies',
    category: 'Quantitative Finance',
    difficulty: 'Advanced',
    duration: '8.5 hours',
    durationHours: 8.5,
    rating: 4.9,
    reviewsCount: 184,
    enrolledCount: 620,
    stage: 'FinTech Analytics',
    instructor: {
      name: 'Dr. Aris Vance',
      title: 'Head of Quantitative Research & Ex-HFT Strategist',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    },
    thumbnailUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=800&q=80',
    tags: ['C++', 'Python', 'Market Microstructure', 'HFT', 'Order Book'],
    isFeatured: true,
    description:
      'Master low-latency order execution, limit order book dynamics, statistical arbitrage, and execution algorithms used by top-tier quantitative hedge funds.',
    outcomes: [
      'Understand Limit Order Book (LOB) mechanics and depth analysis',
      'Implement VWAP, TWAP, and Implementation Shortfall algorithms',
      'Backtest statistical arbitrage and pair trading strategies using Python',
      'Optimize latency and order execution pipelines',
    ],
    modules: [
      {
        moduleId: 'm1',
        title: 'Module 1: Foundations of Market Microstructure',
        duration: '2.5 hours',
        lessons: [
          {
            lessonId: 'l101',
            title: '1.1 Limit Order Books & Matching Engines',
            duration: '35 mins',
            type: 'video',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
            content:
              'In this lesson, we explore how matching engines process bids and asks, FIFO queue priority, price-time priority, and latency impact on fill ratios.',
            resources: [
              { title: 'LOB Mechanics Cheat Sheet (PDF)', url: '#', type: 'pdf' },
              { title: 'Matching Engine Simulator (Python)', url: '#', type: 'code' },
            ],
          },
          {
            lessonId: 'l102',
            title: '1.2 Order Types & Hidden Liquidity (Dark Pools)',
            duration: '45 mins',
            type: 'video',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
            content:
              'Learn about Iceberg orders, Pegged orders, Fill-or-Kill (FOK), and how dark pool execution venues interact with lit exchanges.',
            resources: [{ title: 'Order Execution Taxonomy (PDF)', url: '#', type: 'pdf' }],
          },
          {
            lessonId: 'l103',
            title: '1.3 Market Impact & Slippage Modeling',
            duration: '70 mins',
            type: 'reading',
            videoUrl: '',
            content:
              'Detailed guide on Almgren-Chriss framework for optimal execution and minimizing permanent vs temporary price impact during large orders.',
            resources: [{ title: 'Almgren-Chriss Model Jupyter Notebook', url: '#', type: 'code' }],
          },
        ],
      },
      {
        moduleId: 'm2',
        title: 'Module 2: Statistical Arbitrage & Pair Trading',
        duration: '3 hours',
        lessons: [
          {
            lessonId: 'l201',
            title: '2.1 Cointegration & Mean Reversion Signals',
            duration: '50 mins',
            type: 'video',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
            content:
              'Engage with Augmented Dickey-Fuller (ADF) test, Johansen test, and building Z-score trading triggers across correlated equities.',
            resources: [{ title: 'Cointegrated Pairs Notebook', url: '#', type: 'code' }],
          },
          {
            lessonId: 'l202',
            title: '2.2 Kalman Filters for Dynamic Hedge Ratios',
            duration: '60 mins',
            type: 'video',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
            content:
              'Apply recursive state-space estimation to adjust beta dynamically as market regimes shift over time.',
            resources: [{ title: 'Kalman Filter Python Script', url: '#', type: 'code' }],
          },
        ],
      },
      {
        moduleId: 'm3',
        title: 'Module 3: Low Latency Architecture & Execution',
        duration: '3 hours',
        lessons: [
          {
            lessonId: 'l301',
            title: '3.1 FIX Protocol & Binary Gateway Feeds',
            duration: '60 mins',
            type: 'video',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
            content: 'Understand Financial Information eXchange (FIX) session protocols, message tags, and FPGA acceleration.',
            resources: [{ title: 'FIX Protocol Message Map', url: '#', type: 'pdf' }],
          },
          {
            lessonId: 'l302',
            title: '3.2 Backtesting & Overfitting Safeguards',
            duration: '60 mins',
            type: 'interactive',
            videoUrl: '',
            content: 'Interactive sandbox testing for walk-forward optimization and avoiding look-ahead bias.',
            resources: [{ title: 'Backtest Validation Checklist', url: '#', type: 'pdf' }],
          },
        ],
      },
    ],
  },
  {
    _id: 'c102',
    title: 'Financial Machine Learning & Risk Modeling',
    slug: 'financial-machine-learning-risk-modeling',
    category: 'Financial AI & Analytics',
    difficulty: 'Intermediate',
    duration: '6.5 hours',
    durationHours: 6.5,
    rating: 4.8,
    reviewsCount: 142,
    enrolledCount: 510,
    stage: 'FinTech Analytics',
    instructor: {
      name: 'Elena Rostova',
      title: 'Principal Financial AI Engineer',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    },
    thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    tags: ['Machine Learning', 'Risk Model', 'Credit Scoring', 'Python', 'XGBoost'],
    isFeatured: true,
    description:
      'Apply supervised and unsupervised machine learning algorithms to financial time-series forecasting, credit default prediction, portfolio optimization, and VaR risk calculation.',
    outcomes: [
      'Engineered financial features from tick data and unstructured financial reports',
      'Train LightGBM and XGBoost models for default probability prediction',
      'Calculate Value at Risk (VaR) and Expected Shortfall using Monte Carlo simulations',
      'Mitigate feature importance bias and financial signal noise',
    ],
    modules: [
      {
        moduleId: 'm101',
        title: 'Module 1: Feature Engineering for Financial Time-Series',
        duration: '3 hours',
        lessons: [
          {
            lessonId: 'l401',
            title: '1.1 Stationary Data Transformation & Fractional Differentiation',
            duration: '50 mins',
            type: 'video',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoylikes.mp4',
            content: 'Transform non-stationary asset prices while retaining memory using fractional differentiation techniques.',
            resources: [{ title: 'Fractional Differentiation Notebook', url: '#', type: 'code' }],
          },
          {
            lessonId: 'l402',
            title: '1.2 Triple Barrier Labeling & Meta-Labeling',
            duration: '55 mins',
            type: 'video',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
            content: 'Define price target, stop-loss, and time barriers to generate realistic ML classification labels.',
            resources: [{ title: 'Triple Barrier Python Implementation', url: '#', type: 'code' }],
          },
        ],
      },
      {
        moduleId: 'm102',
        title: 'Module 2: Credit Scoring & Default Forecasting',
        duration: '3.5 hours',
        lessons: [
          {
            lessonId: 'l403',
            title: '2.1 XGBoost & SHAP Values for Credit Approval',
            duration: '60 mins',
            type: 'reading',
            videoUrl: '',
            content: 'Explainable AI in lending: evaluating model decisions with SHAP values for regulatory transparency.',
            resources: [{ title: 'Credit Risk Dataset & SHAP Guide', url: '#', type: 'pdf' }],
          },
        ],
      },
    ],
  },
  {
    _id: 'c103',
    title: 'DeFi Protocols & Smart Contract Auditing',
    slug: 'defi-protocols-smart-contract-auditing',
    category: 'DeFi & Blockchain',
    difficulty: 'Advanced',
    duration: '10 hours',
    durationHours: 10,
    rating: 4.95,
    reviewsCount: 210,
    enrolledCount: 780,
    stage: 'Blockchain & Crypto',
    instructor: {
      name: 'Marcus Vance',
      title: 'Web3 Security Auditor & Founder at ChainGuard',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    },
    thumbnailUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=800&q=80',
    tags: ['Solidity', 'AMM', 'Yield Farming', 'Reentrancy', 'EVM'],
    isFeatured: true,
    description:
      'Deep dive into Automated Market Makers (AMM), Lending pools, Flash loans, and security auditing for EVM smart contracts against reentrancy, flash loan exploits, and front-running.',
    outcomes: [
      'Analyze Uniswap v3 concentrated liquidity mathematical formulas',
      'Audit Solidity code for reentrancy vulnerabilities and integer overflows',
      'Simulate flash loan arbitrage using Foundry and Hardhat',
      'Implement decentralized governance and staking rewards mechanics',
    ],
    modules: [
      {
        moduleId: 'm201',
        title: 'Module 1: Automated Market Makers & Decentralized Exchanges',
        duration: '4 hours',
        lessons: [
          {
            lessonId: 'l501',
            title: '1.1 Constant Product Formula (x * y = k) & Impermanent Loss',
            duration: '60 mins',
            type: 'video',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
            content: 'Step-by-step mathematical breakdown of liquidity pool pricing, slippage, and impermanent loss formulas.',
            resources: [{ title: 'AMM Calculator Tool', url: '#', type: 'code' }],
          },
          {
            lessonId: 'l502',
            title: '1.2 Flash Loans & Arbitrage Mechanics',
            duration: '75 mins',
            type: 'video',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
            content: 'Uncollateralized borrowing within a single EVM transaction block and executing cross-DEX arbitrage.',
            resources: [{ title: 'Flash Loan Template (Solidity)', url: '#', type: 'code' }],
          },
        ],
      },
    ],
  },
  {
    _id: 'c104',
    title: 'RegTech Compliance & Anti-Money Laundering Systems',
    slug: 'regtech-compliance-aml-systems',
    category: 'RegTech & Compliance',
    difficulty: 'Intermediate',
    duration: '5 hours',
    durationHours: 5,
    rating: 4.75,
    reviewsCount: 95,
    enrolledCount: 340,
    stage: 'FinTech Basics',
    instructor: {
      name: 'Sarah Jenkins',
      title: 'Compliance Officer & RegTech Consultant',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
    },
    thumbnailUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80',
    tags: ['RegTech', 'AML', 'KYC', 'Sanction Screening', 'GDPR'],
    isFeatured: false,
    description:
      'Learn how automated KYC/AML verification, transaction monitoring, sanction list screening, and suspicious activity reporting (SAR) work in modern digital banks.',
    outcomes: [
      'Design automated Customer Due Diligence (CDD) and e-KYC pipelines',
      'Implement real-time sanction list fuzzy matching algorithms',
      'Detect anomalous transaction patterns using rule engines',
    ],
    modules: [
      {
        moduleId: 'm301',
        title: 'Module 1: Digital KYC & Identity Verification',
        duration: '2.5 hours',
        lessons: [
          {
            lessonId: 'l601',
            title: '1.1 e-KYC Frameworks & Biometric Liveness Detection',
            duration: '45 mins',
            type: 'video',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
            content: 'Architecting biometric identity verification and document OCR authentication flows.',
            resources: [{ title: 'KYC Workflow Diagram', url: '#', type: 'pdf' }],
          },
        ],
      },
    ],
  },
  {
    _id: 'c105',
    title: 'Digital Payments Architecture & UPI Infrastructure',
    slug: 'digital-payments-architecture-upi',
    category: 'Payments Infrastructure',
    difficulty: 'Beginner',
    duration: '6 hours',
    durationHours: 6,
    rating: 4.88,
    reviewsCount: 160,
    enrolledCount: 890,
    stage: 'Digital Payments',
    instructor: {
      name: 'Rajesh Kumar',
      title: 'Principal Payment Architect',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    },
    thumbnailUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&q=80',
    tags: ['UPI', 'Payment Gateway', 'ISO 20022', 'PCI-DSS', 'Tokenization'],
    isFeatured: true,
    description:
      'Explore core banking switches, payment gateways, card networks (Visa/Mastercard/RuPay), UPI 2.0 architecture, real-time settlement, and security standards.',
    outcomes: [
      'Understand end-to-end payment gateway authorization and settlement flow',
      'Learn UPI 2.0 virtual payment address (VPA) resolution and NPCI switch architecture',
      'Implement PCI-DSS compliant card tokenization',
    ],
    modules: [
      {
        moduleId: 'm401',
        title: 'Module 1: Foundations of Payment Gateways & Switches',
        duration: '3 hours',
        lessons: [
          {
            lessonId: 'l701',
            title: '1.1 Payment Gateway Authorization & Settlement Flow',
            duration: '50 mins',
            type: 'video',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
            content: 'Step-by-step trace of merchant request, gateway router, card network switch, and issuing bank approval.',
            resources: [{ title: 'Payment Switch Flowchart', url: '#', type: 'pdf' }],
          },
        ],
      },
    ],
  },
  {
    _id: 'c106',
    title: 'Core Banking Systems & Neo Banking API Integration',
    slug: 'core-banking-systems-neo-banking-api',
    category: 'Banking & Neo Banking',
    difficulty: 'Intermediate',
    duration: '7 hours',
    durationHours: 7,
    rating: 4.82,
    reviewsCount: 115,
    enrolledCount: 420,
    stage: 'Banking & Neo Banking',
    instructor: {
      name: 'Priya Sundaram',
      title: 'FinTech Engineering Director',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
    },
    thumbnailUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    tags: ['Core Banking', 'REST API', 'Open Banking', 'Ledger', 'Microservices'],
    isFeatured: false,
    description:
      'Build Banking-as-a-Service (BaaS) integrations, real-time double-entry account ledgers, Open Banking APIs, and microservices for modern Neo Banks.',
    outcomes: [
      'Design idempotent double-entry financial ledger database schemas',
      'Integrate Open Banking Account Aggregator (AA) APIs',
      'Implement real-time webhook event handling for card transactions',
    ],
    modules: [
      {
        moduleId: 'm501',
        title: 'Module 1: Double-Entry Ledger & BaaS Architecture',
        duration: '3.5 hours',
        lessons: [
          {
            lessonId: 'l801',
            title: '1.1 Double-Entry Accounting & Ledger Integrity',
            duration: '55 mins',
            type: 'video',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
            content: 'How modern core banking systems prevent balance mismatch and ensure transactional ACID compliance.',
            resources: [{ title: 'Ledger Schema Design', url: '#', type: 'code' }],
          },
        ],
      },
    ],
  },
];
