export const SEEDED_MENTOR_STATS = {
  activeStudents: 48,
  upcomingSessions: 6,
  completedSessions: 124,
  unreadMessages: 5,
};

export const SEEDED_MENTOR_STUDENTS = [
  {
    studentId: 'st_101',
    name: 'Vishaltharshan S',
    email: 'vishal@fintrack.edu',
    avatar: '',
    courseProgress: 88,
    skillScore: 94,
    practiceAccuracy: 92,
    learningStreak: '18 Days',
    lastActive: '10 mins ago',
    currentStage: 'Quantitative Trading',
    mentorshipStatus: 'Active',
    enrolledCourses: ['Algorithmic Trading & High-Frequency Strategies', 'Financial Machine Learning'],
    assessmentScore: '92%',
    strengths: ['Algorithmic Execution', 'Risk Modeling', 'Python Data Processing'],
    weakAreas: ['Smart Contract Security Audits'],
    mentoringHistory: [
      { date: '2026-09-05', topic: 'HFT Strategy Backtesting', notes: 'Excellent execution logic. Advised optimization of order book data feed.' },
      { date: '2026-08-20', topic: 'Quant Portfolio Risk Modeling', notes: 'Reviewed VaR calculation models. Strong statistical grasp.' },
    ],
  },
  {
    studentId: 'st_102',
    name: 'Priya Sharma',
    email: 'priya@fintrack.edu',
    avatar: '',
    courseProgress: 75,
    skillScore: 88,
    practiceAccuracy: 85,
    learningStreak: '12 Days',
    lastActive: '1 hour ago',
    currentStage: 'DeFi & Smart Contracts',
    mentorshipStatus: 'Active',
    enrolledCourses: ['DeFi Protocols & Smart Contract Auditing', 'Banking & Neo Banking'],
    assessmentScore: '86%',
    strengths: ['Solidity Smart Contracts', 'DeFi Liquidity Pools'],
    weakAreas: ['Financial Markets Derivatives'],
    mentoringHistory: [
      { date: '2026-09-01', topic: 'Solidity Reentrancy Vulnerability Review', notes: 'Walked through reentrancy guards and CEI pattern.' },
    ],
  },
  {
    studentId: 'st_103',
    name: 'Rahul Dev',
    email: 'rahul@fintrack.edu',
    avatar: '',
    courseProgress: 64,
    skillScore: 78,
    practiceAccuracy: 76,
    learningStreak: '7 Days',
    lastActive: '3 hours ago',
    currentStage: 'RegTech Compliance',
    mentorshipStatus: 'Active',
    enrolledCourses: ['RegTech Compliance & Anti-Money Laundering', 'Digital Payments'],
    assessmentScore: '74%',
    strengths: ['ISO 20022 Messaging', 'AML Monitoring Systems'],
    weakAreas: ['Cybersecurity Threat Analysis'],
    mentoringHistory: [
      { date: '2026-08-28', topic: 'KYC / AML Data Pipeline Architecture', notes: 'Guided on streaming API compliance integration.' },
    ],
  },
  {
    studentId: 'st_104',
    name: 'Meena Iyer',
    email: 'meena@fintrack.edu',
    avatar: '',
    courseProgress: 92,
    skillScore: 96,
    practiceAccuracy: 95,
    learningStreak: '25 Days',
    lastActive: 'Just now',
    currentStage: 'FinTech Analytics',
    mentorshipStatus: 'Active',
    enrolledCourses: ['Quantitative Portfolio Optimization', 'Financial Machine Learning'],
    assessmentScore: '98%',
    strengths: ['Predictive Credit Scoring', 'ROC-AUC Optimization'],
    weakAreas: ['High-Frequency C++ Networks'],
    mentoringHistory: [],
  },
  {
    studentId: 'st_105',
    name: 'Sandeep Rao',
    email: 'sandeep@fintrack.edu',
    avatar: '',
    courseProgress: 50,
    skillScore: 70,
    practiceAccuracy: 68,
    learningStreak: '4 Days',
    lastActive: 'Yesterday',
    currentStage: 'Digital Payments',
    mentorshipStatus: 'Pending',
    enrolledCourses: ['Digital Payments Infrastructure & Gateway Engineering'],
    assessmentScore: '68%',
    strengths: ['Payment Gateway Protocol API'],
    weakAreas: ['UPI Auto-Pay Mandates', 'Fraud Detection Algorithms'],
    mentoringHistory: [],
  },
];

export const SEEDED_MENTOR_SESSIONS = [
  {
    sessionId: 'sess_m1',
    studentId: 'st_101',
    studentName: 'Vishaltharshan S',
    topic: 'HFT Strategy Review & Backtesting Optimization',
    sessionType: '1-on-1 Mentorship',
    date: '2026-09-12T10:00:00.000Z',
    timeSlot: '10:00 AM - 10:45 AM',
    durationMinutes: 45,
    status: 'Upcoming',
    meetingLink: 'https://meet.fintrack.edu/hft-strategy-review',
    notes: 'Focus on latency reduction in order execution pipeline and order book L2 data parsing.',
    agenda: '1. Review backtest log results\n2. Analyze slippage under volatility\n3. Code optimization tips',
  },
  {
    sessionId: 'sess_m2',
    studentId: 'st_102',
    studentName: 'Priya Sharma',
    topic: 'Quant Portfolio Risk Assessment & VaR Calculation',
    sessionType: 'Code Review',
    date: '2026-09-13T14:30:00.000Z',
    timeSlot: '02:30 PM - 03:15 PM',
    durationMinutes: 45,
    status: 'Upcoming',
    meetingLink: 'https://meet.fintrack.edu/risk-assessment-review',
    notes: 'Review Monte Carlo simulation code for portfolio tail risk.',
    agenda: '1. Audit VaR formulas\n2. Stress testing setup\n3. Q&A',
  },
  {
    sessionId: 'sess_m3',
    studentId: 'st_103',
    studentName: 'Rahul Dev',
    topic: 'RegTech Compliance API Integration Strategy',
    sessionType: 'Project Consultation',
    date: '2026-09-15T11:00:00.000Z',
    timeSlot: '11:00 AM - 11:45 AM',
    durationMinutes: 45,
    status: 'Upcoming',
    meetingLink: 'https://meet.fintrack.edu/regtech-api-consultation',
    notes: 'Discuss real-time transaction screening against sanctions databases.',
    agenda: '1. Architecture diagram review\n2. API rate limiting & security',
  },
  {
    sessionId: 'sess_m0_past',
    studentId: 'st_101',
    studentName: 'Vishaltharshan S',
    topic: 'Algorithmic Execution Baseline Architecture',
    sessionType: '1-on-1 Mentorship',
    date: '2026-09-05T10:00:00.000Z',
    timeSlot: '10:00 AM - 10:45 AM',
    durationMinutes: 45,
    status: 'Completed',
    meetingLink: 'https://meet.fintrack.edu/hft-baseline',
    notes: 'Completed session. Excellent progress.',
    agenda: 'Baseline setup complete.',
  },
];

export const SEEDED_CONNECT_REQUESTS = [
  {
    requestId: 'req_c1',
    studentId: 'st_105',
    studentName: 'Sandeep Rao',
    studentCourse: 'Digital Payments Infrastructure',
    studentSkillScore: '70%',
    requestMessage: 'Hi Mentor, I am seeking guidance on designing scalable Payment Gateway architectures and preparing for Quant FinTech roles.',
    interests: ['Digital Payments', 'UPI Mandates', 'System Architecture'],
    requestedAt: '2026-09-10T09:00:00.000Z',
    status: 'pending',
  },
  {
    requestId: 'req_c2',
    studentId: 'st_106',
    studentName: 'Ananya Verma',
    studentCourse: 'FinTech Analytics & AI',
    studentSkillScore: '82%',
    requestMessage: 'I would love 1-on-1 mentorship regarding machine learning credit default modeling and ROC-AUC optimization.',
    interests: ['FinTech Analytics', 'Risk Modeling', 'Credit Scoring'],
    requestedAt: '2026-09-11T14:20:00.000Z',
    status: 'pending',
  },
];

export const SEEDED_MESSAGES = [
  {
    conversationId: 'conv_101',
    studentId: 'st_101',
    studentName: 'Vishaltharshan S',
    studentAvatar: '',
    onlineStatus: 'online',
    unreadCount: 2,
    lastMessageTime: '10:15 AM',
    messages: [
      { id: 'm1', senderId: 'st_101', text: 'Hello Sir, I have updated the backtesting script with L2 order book data as advised.', timestamp: '10:10 AM' },
      { id: 'm2', senderId: 'st_101', text: 'Could we quickly review the slippage mitigation logic during our upcoming session today?', timestamp: '10:15 AM' },
    ],
  },
  {
    conversationId: 'conv_102',
    studentId: 'st_102',
    studentName: 'Priya Sharma',
    studentAvatar: '',
    onlineStatus: 'offline',
    unreadCount: 1,
    lastMessageTime: 'Yesterday',
    messages: [
      { id: 'm3', senderId: 'mentor_1', text: 'Hi Priya, make sure to bring your Monte Carlo risk model code for tomorrow’s session.', timestamp: 'Yesterday 4:00 PM' },
      { id: 'm4', senderId: 'st_102', text: 'Will do, Sir! The simulation notebook is ready.', timestamp: 'Yesterday 4:30 PM' },
    ],
  },
  {
    conversationId: 'conv_103',
    studentId: 'st_103',
    studentName: 'Rahul Dev',
    studentAvatar: '',
    onlineStatus: 'online',
    unreadCount: 0,
    lastMessageTime: '2 days ago',
    messages: [
      { id: 'm5', senderId: 'st_103', text: 'Thanks for the feedback on the ISO 20022 payload format!', timestamp: '2 days ago' },
      { id: 'm6', senderId: 'mentor_1', text: 'You are welcome Rahul. Keep up the great work.', timestamp: '2 days ago' },
    ],
  },
];

export const SEEDED_MENTOR_PROFILE = {
  avatar: '',
  name: 'Dr. Aris Vance',
  designation: 'Senior FinTech Architect & Principal Quant Developer',
  company: 'Apex Quant Technologies',
  bio: 'Veteran Quantitative Finance strategist with 12+ years of experience designing high-frequency trading engines, automated clearing architectures, and machine learning risk models across global markets.',
  yearsOfExperience: 12,
  specialization: 'Quantitative Trading, High-Frequency Systems & DeFi Protocols',
  skills: ['C++', 'Python Quant Stack', 'HFT Architecture', 'DeFi Protocols', 'ISO 20022', 'Machine Learning Risk Models'],
  languages: ['English', 'Tamil', 'German'],
  sessionTopics: [
    'HFT Strategy Review & Backtesting Optimization',
    'Quant Portfolio Risk Assessment & VaR Calculation',
    'RegTech Compliance API Integration Strategy',
    'DeFi Smart Contract Security & Audit Guidelines',
  ],
  credibility: {
    rating: 4.9,
    totalSessions: 124,
    studentsMentored: 48,
    reviewsCount: 86,
  },
};

export const SEEDED_MENTOR_AVAILABILITY = {
  sessionDurationMinutes: 45,
  maxSessionsPerDay: 4,
  weeklySchedule: [
    {
      day: 'Monday',
      isEnabled: true,
      startTime: '09:00 AM',
      endTime: '05:00 PM',
      slots: [
        { slotId: 'mon_1', time: '09:00 AM - 09:45 AM', isBooked: false },
        { slotId: 'mon_2', time: '10:00 AM - 10:45 AM', isBooked: true },
        { slotId: 'mon_3', time: '02:00 PM - 02:45 PM', isBooked: false },
        { slotId: 'mon_4', time: '04:00 PM - 04:45 PM', isBooked: false },
      ],
    },
    {
      day: 'Tuesday',
      isEnabled: true,
      startTime: '10:00 AM',
      endTime: '06:00 PM',
      slots: [
        { slotId: 'tue_1', time: '10:00 AM - 10:45 AM', isBooked: false },
        { slotId: 'tue_2', time: '02:30 PM - 03:15 PM', isBooked: true },
        { slotId: 'tue_3', time: '04:30 PM - 05:15 PM', isBooked: false },
      ],
    },
    {
      day: 'Wednesday',
      isEnabled: true,
      startTime: '09:00 AM',
      endTime: '05:00 PM',
      slots: [
        { slotId: 'wed_1', time: '09:30 AM - 10:15 AM', isBooked: false },
        { slotId: 'wed_2', time: '11:00 AM - 11:45 AM', isBooked: true },
        { slotId: 'wed_3', time: '03:00 PM - 03:45 PM', isBooked: false },
      ],
    },
    {
      day: 'Thursday',
      isEnabled: true,
      startTime: '10:00 AM',
      endTime: '05:00 PM',
      slots: [
        { slotId: 'thu_1', time: '10:00 AM - 10:45 AM', isBooked: false },
        { slotId: 'thu_2', time: '02:00 PM - 02:45 PM', isBooked: false },
      ],
    },
    {
      day: 'Friday',
      isEnabled: true,
      startTime: '09:00 AM',
      endTime: '04:00 PM',
      slots: [
        { slotId: 'fri_1', time: '10:00 AM - 10:45 AM', isBooked: false },
        { slotId: 'fri_2', time: '02:00 PM - 02:45 PM', isBooked: false },
      ],
    },
    {
      day: 'Saturday',
      isEnabled: false,
      startTime: '10:00 AM',
      endTime: '02:00 PM',
      slots: [],
    },
    {
      day: 'Sunday',
      isEnabled: false,
      startTime: '10:00 AM',
      endTime: '02:00 PM',
      slots: [],
    },
  ],
};
