export const SEEDED_QUESTIONS = [
  // 1. Digital Payments
  {
    questionId: 'q_dp_1',
    topic: 'Digital Payments',
    difficulty: 'Beginner',
    questionText: 'What is the primary role of a Payment Gateway in an online transaction ecosystem?',
    options: [
      { id: 'opt_1', text: 'To issue credit cards directly to consumers', isCorrect: false },
      { id: 'opt_2', text: 'To securely capture, encrypt, and transmit customer payment credentials to the acquiring bank', isCorrect: true },
      { id: 'opt_3', text: 'To print physical receipts for e-commerce transactions', isCorrect: false },
      { id: 'opt_4', text: 'To manage physical currency distribution in ATM networks', isCorrect: false },
    ],
    explanation: 'A payment gateway acts as an encrypted conduit transmitting payment details safely between the merchant store, acquirer, and issuing bank.',
    marks: 1,
  },
  {
    questionId: 'q_dp_2',
    topic: 'Digital Payments',
    difficulty: 'Intermediate',
    questionText: 'In ISO 20022 messaging standards for digital payments, what key structural benefit improves international settlement speed?',
    options: [
      { id: 'opt_1', text: 'Use of plain unformatted text messages', isCorrect: false },
      { id: 'opt_2', text: 'Rich, structured XML/JSON data elements containing complete sender and beneficiary metadata', isCorrect: true },
      { id: 'opt_3', text: 'Elimination of digital signatures', isCorrect: false },
      { id: 'opt_4', text: 'Limiting payload sizes to under 100 bytes', isCorrect: false },
    ],
    explanation: 'ISO 20022 provides standardized, rich data structures that prevent transaction flags, automated reconciliation errors, and manual clearing intervention.',
    marks: 2,
  },
  {
    questionId: 'q_dp_3',
    topic: 'Digital Payments',
    difficulty: 'Advanced',
    questionText: 'Which entity bears financial fraud liability during a card-present transaction using EMV chip technology if the merchant bypasses chip verification?',
    options: [
      { id: 'opt_1', text: 'The cardholder', isCorrect: false },
      { id: 'opt_2', text: 'The merchant acquiring bank or merchant', isCorrect: true },
      { id: 'opt_3', text: 'The central bank', isCorrect: false },
      { id: 'opt_4', text: 'The card manufacturing factory', isCorrect: false },
    ],
    explanation: 'Under EMV Liability Shift rules, the party supporting the less secure payment technology (e.g., magnetic stripe fallback instead of chip processing) absorbs counterfeit fraud liability.',
    marks: 3,
  },

  // 2. UPI
  {
    questionId: 'q_upi_1',
    topic: 'UPI',
    difficulty: 'Beginner',
    questionText: 'What parameter allows a UPI user to receive funds without revealing their sensitive bank account number or IFSC code?',
    options: [
      { id: 'opt_1', text: 'Virtual Payment Address (VPA / UPI ID)', isCorrect: true },
      { id: 'opt_2', text: 'Debit Card CVV', isCorrect: false },
      { id: 'opt_3', text: 'Aadhaar OTP', isCorrect: false },
      { id: 'opt_4', text: 'Net Banking Password', isCorrect: false },
    ],
    explanation: 'A Virtual Payment Address (VPA) maps securely to the underlying bank account, preserving financial privacy during peer-to-peer and merchant payments.',
    marks: 1,
  },
  {
    questionId: 'q_upi_2',
    topic: 'UPI',
    difficulty: 'Intermediate',
    questionText: 'How does the UPI 2.0 "Auto-Pay" mandate feature protect subscription users during recurring payments?',
    options: [
      { id: 'opt_1', text: 'By requiring a physical signature for every monthly billing cycle', isCorrect: false },
      { id: 'opt_2', text: 'By allowing students/users to set pre-authorized debit caps and revoke mandates at any time via their app', isCorrect: true },
      { id: 'opt_3', text: 'By converting recurring payments into cryptocurrency transfers', isCorrect: false },
      { id: 'opt_4', text: 'By bypassing bank authorization entirely', isCorrect: false },
    ],
    explanation: 'UPI Auto-Pay lets users set explicit execution limits, start/end dates, and grants full control to pause or cancel mandates instantly.',
    marks: 2,
  },

  // 3. Banking & Neo Banking
  {
    questionId: 'q_bnb_1',
    topic: 'Banking & Neo Banking',
    difficulty: 'Beginner',
    questionText: 'What is the fundamental architectural difference between traditional banks and Neo Banks?',
    options: [
      { id: 'opt_1', text: 'Neo Banks operate without physical branch networks through digital-first API platforms', isCorrect: true },
      { id: 'opt_2', text: 'Traditional banks cannot offer mobile apps', isCorrect: false },
      { id: 'opt_3', text: 'Neo Banks are exempt from government regulatory compliance', isCorrect: false },
      { id: 'opt_4', text: 'Traditional banks do not handle paper currency', isCorrect: false },
    ],
    explanation: 'Neo Banks leverage cloud-native infrastructure, Open Banking APIs, and partner bank licenses without maintaining expensive brick-and-mortar branches.',
    marks: 1,
  },
  {
    questionId: 'q_bnb_2',
    topic: 'Banking & Neo Banking',
    difficulty: 'Intermediate',
    questionText: 'In Open Banking frameworks, how do fintech applications securely access customer bank data without storing user banking passwords?',
    options: [
      { id: 'opt_1', text: 'Through OAuth 2.0 authorization tokens and consent management frameworks', isCorrect: true },
      { id: 'opt_2', text: 'By scraping plain-text credentials stored in browser cookies', isCorrect: false },
      { id: 'opt_3', text: 'Via unencrypted email attachments', isCorrect: false },
      { id: 'opt_4', text: 'Using static hardcoded access keys', isCorrect: false },
    ],
    explanation: 'OAuth 2.0 enables scoped, time-bound access authorization tokens issued directly by banks upon explicit customer consent.',
    marks: 2,
  },

  // 4. Blockchain & Crypto
  {
    questionId: 'q_bc_1',
    topic: 'Blockchain & Crypto',
    difficulty: 'Beginner',
    questionText: 'What property makes data stored on a decentralized permissionless blockchain resistant to unauthorized alteration?',
    options: [
      { id: 'opt_1', text: 'Immutability guaranteed by cryptographic hashing and distributed consensus', isCorrect: true },
      { id: 'opt_2', text: 'Centralized administrator approval for edits', isCorrect: false },
      { id: 'opt_3', text: 'Frequent server reboots by network owners', isCorrect: false },
      { id: 'opt_4', text: 'Deleting historic blocks every 24 hours', isCorrect: false },
    ],
    explanation: 'Chain hashes link each block to the previous block; tampering with any record invalidates subsequent block hashes across network nodes.',
    marks: 1,
  },
  {
    questionId: 'q_bc_2',
    topic: 'Blockchain & Crypto',
    difficulty: 'Advanced',
    questionText: 'In DeFi lending protocols, what mechanism prevents system insolvency when an under-collateralized loan value drops below threshold boundaries?',
    options: [
      { id: 'opt_1', text: 'Manual loan forgiveness by protocol founders', isCorrect: false },
      { id: 'opt_2', text: 'Automated liquidator bots liquidating collateral assets at a discount before debt exceeds asset value', isCorrect: true },
      { id: 'opt_3', text: 'Printing unbacked fiat currency', isCorrect: false },
      { id: 'opt_4', text: 'Freezing user browser windows', isCorrect: false },
    ],
    explanation: 'Smart contract liquidation thresholds allow automated arbitrage bots to pay off bad debt and claim collateral, keeping protocols solvent.',
    marks: 3,
  },

  // 5. Cybersecurity
  {
    questionId: 'q_sec_1',
    topic: 'Cybersecurity',
    difficulty: 'Beginner',
    questionText: 'What security practice prevents unauthorized account takeovers even if an attacker discovers a student’s account password?',
    options: [
      { id: 'opt_1', text: 'Multi-Factor Authentication (MFA / 2FA)', isCorrect: true },
      { id: 'opt_2', text: 'Disabling firewall software', isCorrect: false },
      { id: 'opt_3', text: 'Sharing passwords over public Wi-Fi', isCorrect: false },
      { id: 'opt_4', text: 'Using dictionary words as passwords', isCorrect: false },
    ],
    explanation: 'Multi-Factor Authentication requires a second independent credential (e.g., authenticator app TOTP or SMS OTP) alongside the password.',
    marks: 1,
  },
  {
    questionId: 'q_sec_2',
    topic: 'Cybersecurity',
    difficulty: 'Intermediate',
    questionText: 'Which attack vector involves tricking banking users into entering credentials on a fraudulent replica website?',
    options: [
      { id: 'opt_1', text: 'Phishing / Social Engineering', isCorrect: true },
      { id: 'opt_2', text: 'SQL Injection', isCorrect: false },
      { id: 'opt_3', text: 'Buffer Overflow', isCorrect: false },
      { id: 'opt_4', text: 'Distributed Denial of Service (DDoS)', isCorrect: false },
    ],
    explanation: 'Phishing deceives victims into providing confidential credentials by masquerading as a legitimate financial entity.',
    marks: 2,
  },

  // 6. Financial Markets
  {
    questionId: 'q_fm_1',
    topic: 'Financial Markets',
    difficulty: 'Intermediate',
    questionText: 'What does the Bid-Ask Spread represent in high-frequency equity order books?',
    options: [
      { id: 'opt_1', text: 'The total tax rate paid on stock dividends', isCorrect: false },
      { id: 'opt_2', text: 'The difference between the highest price a buyer is willing to pay and the lowest price a seller is willing to accept', isCorrect: true },
      { id: 'opt_3', text: 'The fee charged by broker mobile applications', isCorrect: false },
      { id: 'opt_4', text: 'The percentage growth rate of stock indices', isCorrect: false },
    ],
    explanation: 'The bid-ask spread reflects market liquidity and transaction costs for immediate buy and sell orders in financial markets.',
    marks: 2,
  },

  // 7. FinTech Analytics
  {
    questionId: 'q_fa_1',
    topic: 'FinTech Analytics',
    difficulty: 'Intermediate',
    questionText: 'Which metric is widely used in Machine Learning credit risk models to assess a binary classifier’s ability to distinguish default vs. non-default borrowers?',
    options: [
      { id: 'opt_1', text: 'AUC-ROC (Area Under the Receiver Operating Characteristic Curve)', isCorrect: true },
      { id: 'opt_2', text: 'Gross Domestic Product (GDP)', isCorrect: false },
      { id: 'opt_3', text: 'Price-to-Earnings Ratio', isCorrect: false },
      { id: 'opt_4', text: 'PageRank Score', isCorrect: false },
    ],
    explanation: 'AUC-ROC measures trade-offs between true positive rate (detecting defaults) and false positive rate across various decision thresholds.',
    marks: 2,
  },

  // 8. InsurTech
  {
    questionId: 'q_it_1',
    topic: 'InsurTech',
    difficulty: 'Beginner',
    questionText: 'How does Telematics IoT device integration transform motor insurance pricing model algorithms?',
    options: [
      { id: 'opt_1', text: 'By replacing risk modeling with uniform fixed fees for all drivers', isCorrect: false },
      { id: 'opt_2', text: 'By enabling Usage-Based Insurance (UBI) based on real-time driving behavior telemetry', isCorrect: true },
      { id: 'opt_3', text: 'By eliminating insurance policies completely', isCorrect: false },
      { id: 'opt_4', text: 'By forcing drivers to purchase daily physical tokens', isCorrect: false },
    ],
    explanation: 'Telematics devices record speed, braking habits, and mileage to offer tailored, behavior-based insurance premiums.',
    marks: 1,
  },
];

export const SEEDED_ASSESSMENTS = [
  {
    assessmentId: 'asm_101',
    title: 'FinTech Core Certification Exam 2026',
    topic: 'Digital Payments & Banking',
    description: 'Comprehensive baseline assessment evaluating core digital payment ecosystems, UPI mandates, and Neo Banking architecture.',
    instructions: [
      'Total duration: 30 minutes.',
      'Contains 10 multiple-choice questions.',
      'Passing score is 70% (70 / 100 marks).',
      'You can mark questions for review and navigate freely using the question palette.',
      'Submit before timer expires.',
    ],
    difficulty: 'Intermediate',
    durationMinutes: 30,
    totalQuestions: 10,
    totalMarks: 100,
    passingPercentage: 70,
    topicsCovered: ['Digital Payments', 'UPI', 'Banking & Neo Banking'],
    questionIds: ['q_dp_1', 'q_dp_2', 'q_dp_3', 'q_upi_1', 'q_upi_2', 'q_bnb_1', 'q_bnb_2'],
  },
  {
    assessmentId: 'asm_102',
    title: 'Blockchain & Smart Contract Security Assessment',
    topic: 'Blockchain & Cybersecurity',
    description: 'Advanced assessment testing decentralized finance protocol risks, immutability, smart contract audit vulnerabilities, and multi-factor security.',
    instructions: [
      'Total duration: 45 minutes.',
      'Contains 8 advanced scenario questions.',
      'Passing score is 75%.',
      'Ensure high clarity in cryptographic concepts before starting.',
    ],
    difficulty: 'Advanced',
    durationMinutes: 45,
    totalQuestions: 8,
    totalMarks: 100,
    passingPercentage: 75,
    topicsCovered: ['Blockchain & Crypto', 'Cybersecurity'],
    questionIds: ['q_bc_1', 'q_bc_2', 'q_sec_1', 'q_sec_2'],
  },
  {
    assessmentId: 'asm_103',
    title: 'FinTech Analytics & Risk Modeling Fundamentals',
    topic: 'FinTech Analytics & Markets',
    description: 'Practical evaluation covering machine learning credit risk algorithms, bid-ask spread analytics, and predictive financial modeling.',
    instructions: [
      'Total duration: 25 minutes.',
      'Contains 10 questions.',
      'Passing score is 65%.',
    ],
    difficulty: 'Intermediate',
    durationMinutes: 25,
    totalQuestions: 10,
    totalMarks: 100,
    passingPercentage: 65,
    topicsCovered: ['FinTech Analytics', 'Financial Markets', 'InsurTech'],
    questionIds: ['q_fm_1', 'q_fa_1', 'q_it_1'],
  },
];

export const SEEDED_EXAMS = [
  {
    examId: 'exam_201',
    title: 'Mid-Term FinTech Engineering Examination',
    course: 'Algorithmic Trading & High-Frequency Strategies',
    date: '2026-09-25T10:00:00.000Z',
    duration: '60 mins',
    status: 'Upcoming',
    resultStatus: 'Not Attempted',
    totalMarks: 100,
  },
  {
    examId: 'exam_202',
    title: 'National Naan Mudhalvan FinTech Skill Benchmark',
    course: 'FinTrack Comprehensive Skill Evaluation',
    date: '2026-09-18T14:30:00.000Z',
    duration: '90 mins',
    status: 'Scheduled',
    resultStatus: 'Not Attempted',
    totalMarks: 150,
  },
  {
    examId: 'exam_200',
    title: 'Baseline Digital Banking Quiz',
    course: 'Banking & Neo Banking Architecture',
    date: '2026-09-02T11:00:00.000Z',
    duration: '30 mins',
    status: 'Completed',
    resultStatus: 'Passed (88%)',
    totalMarks: 50,
  },
];

export const SEEDED_ASSIGNMENTS = [
  {
    assignmentId: 'asg_301',
    title: 'Design an ISO 20022 Compliant Payment Message Payload',
    courseOrTopic: 'Digital Payments',
    dueDate: '2026-09-20T23:59:59.000Z',
    maxMarks: 100,
    submissionStatus: 'Pending',
    marks: null,
    feedback: '',
    description: 'Draft an XML/JSON payment initiation payload adhering to ISO 20022 pacs.008 format. Include debtor, creditor, remittance information, and clearing system identifiers.',
    instructions: 'Paste your JSON payload or structured code in the text box below. Clear documentation of elements is required for full credit.',
  },
  {
    assignmentId: 'asg_302',
    title: 'Credit Risk Classification Model Analysis',
    courseOrTopic: 'FinTech Analytics',
    dueDate: '2026-09-28T23:59:59.000Z',
    maxMarks: 100,
    submissionStatus: 'Submitted',
    marks: 92,
    feedback: 'Excellent evaluation of ROC-AUC metrics and handling of class imbalance in loan default datasets!',
    description: 'Compare Logistic Regression vs Random Forest classifiers on a synthetic credit dataset. Evaluate Precision, Recall, and AUC-ROC score.',
    instructions: 'Submit a concise executive summary (300-500 words) with key performance metric comparisons.',
  },
];

export const SEEDED_PERFORMANCE_STATS = {
  overallPerformanceScore: 78,
  practiceAccuracy: 82,
  assessmentScore: 76,
  questionsSolved: 145,
  learningToPracticeConversion: '84%',
  weeklyActivity: [
    { day: 'Mon', solved: 18, accuracy: 85 },
    { day: 'Tue', solved: 24, accuracy: 80 },
    { day: 'Wed', solved: 15, accuracy: 78 },
    { day: 'Thu', solved: 30, accuracy: 88 },
    { day: 'Fri', solved: 22, accuracy: 90 },
    { day: 'Sat', solved: 14, accuracy: 75 },
    { day: 'Sun', solved: 22, accuracy: 82 },
  ],
  topicPerformance: [
    { topic: 'Digital Payments', accuracy: 88, status: 'Strong', solved: 35 },
    { topic: 'UPI', accuracy: 92, status: 'Strong', solved: 28 },
    { topic: 'Banking & Neo Banking', accuracy: 84, status: 'Good', solved: 25 },
    { topic: 'Blockchain & Crypto', accuracy: 76, status: 'Good', solved: 20 },
    { topic: 'Financial Markets', accuracy: 72, status: 'Good', solved: 15 },
    { topic: 'Cybersecurity', accuracy: 65, status: 'Weak', solved: 12 },
    { topic: 'FinTech Analytics', accuracy: 70, status: 'Good', solved: 10 },
  ],
  strengthAreas: ['Digital Payments', 'UPI', 'Banking & Neo Banking'],
  weakAreas: ['Cybersecurity', 'Financial Markets'],
  improvementTrend: '+12% accuracy gain in last 14 days',
  smartRecommendations: [
    {
      id: 'rec_1',
      weakTopic: 'Cybersecurity',
      title: 'Strengthen Cybersecurity & Defensive FinTech',
      description: 'Your Cybersecurity accuracy is 65%, which is lower than your other FinTech topics.',
      recommendedCourse: 'FinTech Security & Defensive Architecture',
      recommendedCourseId: 'c104',
      practiceTopic: 'Cybersecurity',
      assessmentId: 'asm_102',
      actionText: 'Start Cybersecurity Practice Set',
    },
    {
      id: 'rec_2',
      weakTopic: 'Financial Markets',
      title: 'Master Order Book Mechanics & Market Microstructure',
      description: 'Boost your score in bid-ask spreads and liquidity risk management.',
      recommendedCourse: 'Algorithmic Trading & High-Frequency Strategies',
      recommendedCourseId: 'c101',
      practiceTopic: 'Financial Markets',
      assessmentId: 'asm_103',
      actionText: 'Attempt Market Microstructure Quiz',
    },
  ],
};
