export const SEEDED_RECRUITER_STATS = {
  activeJobs: 8,
  totalApplicants: 142,
  shortlistedCandidates: 18,
  interviewsScheduled: 6,
  hires: 12,
  availableCandidates: 340,
};

export const SEEDED_JOBS = [
  {
    jobId: 'job_101',
    title: 'Junior Quantitative Developer',
    company: 'Nexus Financial Solutions',
    companyLogo: '',
    location: 'Chennai, India',
    workMode: 'Hybrid',
    employmentType: 'Full-time',
    experienceLevel: '0-2 Years',
    salaryRange: '₹12,00,000 - ₹18,00,000 P.A.',
    requiredSkills: ['Python', 'C++', 'Financial Markets', 'FinTech Analytics'],
    preferredSkills: ['High-Frequency Backtesting', 'SQL', 'Git'],
    description: 'We are seeking a high-caliber Junior Quant Engineer to build low-latency trading algorithms, optimize backtesting engines, and develop risk analytics dashboards.',
    responsibilities: [
      'Implement data ingestion pipelines for tick-level L2 market feeds.',
      'Optimize backtesting simulations using Python/NumPy.',
      'Collaborate with Senior Risk Officers to calculate VaR metrics.',
    ],
    requirements: [
      'Strong grasp of data structures, algorithms, and financial mathematics.',
      'Proficiency in Python and basic C++.',
      'Demonstrated project work in quantitative finance or algorithmic trading.',
    ],
    applicationDeadline: '2026-10-15T23:59:59.000Z',
    status: 'ACTIVE',
    applicantsCount: 42,
    shortlistedCount: 6,
    interviewCount: 3,
    postedAt: '2026-09-08T10:00:00.000Z',
  },
  {
    jobId: 'job_102',
    title: 'FinTech Compliance & ISO 20022 Specialist',
    company: 'PayGlobe Global Payments',
    companyLogo: '',
    location: 'Bengaluru, India',
    workMode: 'On-site',
    employmentType: 'Full-time',
    experienceLevel: '1-3 Years',
    salaryRange: '₹10,00,000 - ₹14,00,000 P.A.',
    requiredSkills: ['ISO 20022', 'Digital Payments', 'RegTech Compliance', 'UPI'],
    preferredSkills: ['AML Screening APIs', 'SQL'],
    description: 'Join our international remittance engineering group responsible for ISO 20022 message transformation, transaction monitoring, and anti-money laundering API compliance.',
    responsibilities: [
      'Audit pacs.008 and pain.001 XML/JSON payment payloads.',
      'Integrate automated real-time transaction screening APIs.',
      'Collaborate with partner banks during cross-border settlement onboarding.',
    ],
    requirements: [
      'Solid understanding of digital payments infrastructure and UPI 2.0 Auto-Pay.',
      'Familiarity with regulatory frameworks and ISO 20022 schemas.',
    ],
    applicationDeadline: '2026-10-20T23:59:59.000Z',
    status: 'ACTIVE',
    applicantsCount: 28,
    shortlistedCount: 4,
    interviewCount: 2,
    postedAt: '2026-09-05T14:30:00.000Z',
  },
  {
    jobId: 'job_103',
    title: 'DeFi Smart Contract Security Intern',
    company: 'BlockScale Labs',
    companyLogo: '',
    location: 'Remote',
    workMode: 'Remote',
    employmentType: 'Internship',
    experienceLevel: 'Fresher / Student',
    salaryRange: '₹35,000 / month Stipend',
    requiredSkills: ['Blockchain & Crypto', 'Solidity', 'Cybersecurity'],
    preferredSkills: ['Smart Contract Auditing', 'Web3.js'],
    description: '6-month intensive research internship auditing decentralized finance smart contracts, identifying reentrancy vulnerabilities, and writing security unit test suites.',
    responsibilities: [
      'Perform static analysis on Solidity smart contract codebases.',
      'Draft security vulnerability reports.',
    ],
    requirements: [
      'Completed coursework in DeFi Protocols & Blockchain Security.',
      'Hands-on experience writing unit tests in Hardhat / Foundry.',
    ],
    applicationDeadline: '2026-09-30T23:59:59.000Z',
    status: 'ACTIVE',
    applicantsCount: 54,
    shortlistedCount: 8,
    interviewCount: 1,
    postedAt: '2026-09-02T11:00:00.000Z',
  },
];

export const SEEDED_CANDIDATES = [
  {
    candidateId: 'cand_201',
    studentId: 'st_101',
    name: 'Vishaltharshan S',
    email: 'vishal@fintrack.edu',
    avatar: '',
    education: 'B.Tech CS & FinTech (Naan Mudhalvan Cohort Top 5%)',
    location: 'Chennai, India',
    experience: 'Quant Research Intern (6 mos)',
    skills: ['Python', 'C++', 'Financial Markets', 'FinTech Analytics', 'SQL'],
    overallSkillScore: 94,
    practiceAccuracy: 92,
    assessmentScore: '92%',
    careerReadinessScore: 92,
    verifiedBadge: 'Naan Mudhalvan Gold Verified',
    availability: 'Immediate (0-15 days)',
    careerObjective: 'Quant Engineer specializing in order execution algorithms and financial machine learning.',
    strengths: ['High-Frequency Backtesting', 'Algorithmic Execution', 'VaR Tail Risk Modeling'],
    weakAreas: ['Smart Contract Security Audits'],
    applicationHistory: [
      { jobId: 'job_101', jobTitle: 'Junior Quantitative Developer', status: 'SHORTLISTED', appliedDate: '2026-09-09' },
    ],
  },
  {
    candidateId: 'cand_202',
    studentId: 'st_102',
    name: 'Priya Sharma',
    email: 'priya@fintrack.edu',
    avatar: '',
    education: 'B.E. Information Technology',
    location: 'Bengaluru, India',
    experience: 'Web3 Developer Intern (4 mos)',
    skills: ['Solidity', 'Blockchain & Crypto', 'Cybersecurity', 'Python'],
    overallSkillScore: 88,
    practiceAccuracy: 85,
    assessmentScore: '86%',
    careerReadinessScore: 85,
    verifiedBadge: 'Naan Mudhalvan Verified',
    availability: '15-30 days',
    careerObjective: 'Smart Contract Auditor specializing in EVM security and DeFi liquidity protocol auditing.',
    strengths: ['Solidity Smart Contracts', 'DeFi Protocols'],
    weakAreas: ['Financial Markets Derivatives'],
    applicationHistory: [
      { jobId: 'job_103', jobTitle: 'DeFi Smart Contract Security Intern', status: 'INTERVIEW', appliedDate: '2026-09-04' },
    ],
  },
  {
    candidateId: 'cand_203',
    studentId: 'st_103',
    name: 'Rahul Dev',
    email: 'rahul@fintrack.edu',
    avatar: '',
    education: 'B.Tech Information Science',
    location: 'Hyderabad, India',
    experience: 'Software Engineering Trainee',
    skills: ['ISO 20022', 'Digital Payments', 'RegTech Compliance', 'UPI'],
    overallSkillScore: 78,
    practiceAccuracy: 76,
    assessmentScore: '74%',
    careerReadinessScore: 80,
    verifiedBadge: 'Naan Mudhalvan Verified',
    availability: 'Immediate',
    careerObjective: 'Payment Systems Engineer focused on ISO 20022 message transformation and cross-border settlement.',
    strengths: ['ISO 20022 Messaging', 'AML Monitoring APIs'],
    weakAreas: ['C++ High Frequency Networks'],
    applicationHistory: [
      { jobId: 'job_102', jobTitle: 'FinTech Compliance Specialist', status: 'SCREENING', appliedDate: '2026-09-06' },
    ],
  },
];

export const SEEDED_SKILL_PASSPORT = {
  studentId: 'st_101',
  studentName: 'Vishaltharshan S',
  verifiedBadgeTier: 'Naan Mudhalvan Gold Verified',
  overallSkillScore: 94,
  careerReadinessScore: 92,
  verifiedSkills: [
    { skill: 'Python for Finance', proficiency: 92, verificationSource: 'Verified through FinTrack Assessment', level: 'Advanced' },
    { skill: 'Financial Markets & Market Microstructure', proficiency: 88, verificationSource: 'Verified through Practice Benchmark', level: 'Advanced' },
    { skill: 'FinTech Analytics & Risk Modeling', proficiency: 90, verificationSource: 'Verified through Assessment', level: 'Advanced' },
    { skill: 'Digital Payments Infrastructure', proficiency: 85, verificationSource: 'Verified through Course Evaluation', level: 'Intermediate' },
    { skill: 'SQL & Database Querying', proficiency: 82, verificationSource: 'Verified through Practical Assignment', level: 'Intermediate' },
  ],
  certifications: [
    { title: 'Naan Mudhalvan Advanced FinTech Professional', issuer: 'TN Skill Development Corporation', issueDate: 'August 2026', credentialUrl: 'https://credentials.fintrack.edu/verify/NM-9921' },
    { title: 'Quantitative Trading & HFT Architecture', issuer: 'FinTrack Edu Academy', issueDate: 'July 2026', credentialUrl: 'https://credentials.fintrack.edu/verify/FT-4412' },
  ],
  projects: [
    { title: 'High-Frequency Order Book Backtester in Python', techStack: ['Python', 'NumPy', 'Pandas'], description: 'Engineered a backtesting framework processing L2 tick data with slippage simulation.', githubUrl: 'https://github.com/example/hft-backtester' },
    { title: 'ISO 20022 Payment Payload Validator API', techStack: ['Express', 'Node.js', 'XML Schema'], description: 'Built pacs.008 schema validation service with real-time compliance checks.', githubUrl: 'https://github.com/example/iso20022-validator' },
  ],
  badges: ['Top 5% Cohort Percentile', '18-Day Learning Streak', 'Mastery in Algorithmic Execution'],
};

export const SEEDED_CAREER_PROFILE = {
  studentId: 'st_101',
  careerObjective: 'Aspiring Quantitative Developer seeking roles in algorithmic trading, market microstructure, and financial analytics.',
  preferredRoles: ['Junior Quantitative Developer', 'FinTech Analytics Engineer', 'Algorithmic Trader'],
  preferredIndustries: ['Quantitative Finance', 'Investment Banking', 'Neo Banking'],
  preferredLocations: ['Chennai', 'Bengaluru', 'Remote'],
  workModePreference: 'Hybrid',
  skills: ['Python', 'C++', 'Financial Markets', 'FinTech Analytics', 'SQL'],
  resumeUrl: 'fintrack_verified_resume.pdf',
  portfolioLinks: [
    { title: 'GitHub Portfolio', url: 'https://github.com/example' },
    { title: 'LinkedIn Profile', url: 'https://linkedin.com/in/example' },
  ],
  availability: 'Immediate (0-15 days)',
  careerReadinessScore: 92,
  readinessChecklist: [
    { item: 'Verified Skill Passport', status: 'Completed', passed: true },
    { item: 'Baseline Assessment Score (80%+)', status: 'Passed (92%)', passed: true },
    { item: 'Practical Capstone Project', status: 'Completed', passed: true },
    { item: 'Uploaded Verified Resume', status: 'Uploaded', passed: true },
    { item: 'Mock Interview Practice', status: 'Recommended Action', passed: false },
  ],
};

export const SEEDED_APPLICATIONS = [
  {
    applicationId: 'app_301',
    jobId: 'job_101',
    jobTitle: 'Junior Quantitative Developer',
    company: 'Nexus Financial Solutions',
    candidateId: 'cand_201',
    candidateName: 'Vishaltharshan S',
    candidateEmail: 'vishal@fintrack.edu',
    appliedDate: '2026-09-09T10:00:00.000Z',
    status: 'SHORTLISTED',
    skillMatchPercentage: 94,
    assessmentScore: '92%',
    coverMessage: 'I have built a Python high-frequency backtester processing L2 market data feeds and scored 94% in the FinTrack Quantitative Trading assessment.',
  },
  {
    applicationId: 'app_302',
    jobId: 'job_102',
    jobTitle: 'FinTech Compliance Specialist',
    company: 'PayGlobe Global Payments',
    candidateId: 'cand_203',
    candidateName: 'Rahul Dev',
    candidateEmail: 'rahul@fintrack.edu',
    appliedDate: '2026-09-06T14:00:00.000Z',
    status: 'SCREENING',
    skillMatchPercentage: 88,
    assessmentScore: '74%',
    coverMessage: 'Eager to apply ISO 20022 schema validation and AML tracking systems in enterprise payment rails.',
  },
  {
    applicationId: 'app_303',
    jobId: 'job_103',
    jobTitle: 'DeFi Smart Contract Security Intern',
    company: 'BlockScale Labs',
    candidateId: 'cand_202',
    candidateName: 'Priya Sharma',
    candidateEmail: 'priya@fintrack.edu',
    appliedDate: '2026-09-04T11:30:00.000Z',
    status: 'INTERVIEW',
    skillMatchPercentage: 92,
    assessmentScore: '86%',
    coverMessage: 'I specialize in Solidity reentrancy guards and smart contract audit test suites.',
  },
];

export const SEEDED_INTERVIEWS = [
  {
    interviewId: 'int_401',
    jobId: 'job_103',
    jobTitle: 'DeFi Smart Contract Security Intern',
    candidateId: 'cand_202',
    candidateName: 'Priya Sharma',
    recruiterId: 'rec_101',
    recruiterName: 'Sarah Jenkins',
    interviewType: 'Technical Screening',
    date: '2026-09-14T11:00:00.000Z',
    timeSlot: '11:00 AM - 11:45 AM',
    durationMinutes: 45,
    meetingLink: 'https://meet.fintrack.edu/interview-room-103',
    notes: 'Focus on Solidity vulnerability detection and unit testing in Hardhat.',
    status: 'SCHEDULED',
  },
  {
    interviewId: 'int_402',
    jobId: 'job_101',
    jobTitle: 'Junior Quantitative Developer',
    candidateId: 'cand_201',
    candidateName: 'Vishaltharshan S',
    recruiterId: 'rec_101',
    recruiterName: 'Sarah Jenkins',
    interviewType: 'Coding Assessment Review',
    date: '2026-09-16T15:00:00.000Z',
    timeSlot: '03:00 PM - 03:45 PM',
    durationMinutes: 45,
    meetingLink: 'https://meet.fintrack.edu/interview-room-101',
    notes: 'Review backtesting repository and VaR risk calculation logic.',
    status: 'SCHEDULED',
  },
];

export const SEEDED_RECRUITER_PROFILE = {
  name: 'Sarah Jenkins',
  company: 'Nexus Financial Solutions',
  designation: 'Talent Acquisition Lead — FinTech & Quant Hiring',
  email: 'sarah.jenkins@nexusfintech.example.com',
  phone: '+91 98765 43210',
  companyDescription: 'Nexus Financial Solutions is a global leader in high-frequency trading infrastructure, digital banking APIs, and quantitative risk software.',
  industry: 'Quantitative Finance & Digital Banking',
  companyLogo: '',
  hiringPreferences: ['Quantitative Engineering', 'ISO 20022 Compliance', 'DeFi Security'],
};

export const SEEDED_RECRUITER_MESSAGES = [
  {
    conversationId: 'rconv_1',
    candidateId: 'cand_201',
    candidateName: 'Vishaltharshan S',
    lastMessageTime: '11:20 AM',
    unreadCount: 1,
    messages: [
      { id: 'rm1', senderId: 'rec_101', text: 'Hello Vishaltharshan, your Skill Passport in Quantitative Trading is impressive. We shortlisted your application for Junior Quant Developer.', timestamp: '11:00 AM' },
      { id: 'rm2', senderId: 'cand_201', text: 'Thank you Sarah! I look forward to discussing my backtesting project.', timestamp: '11:20 AM' },
    ],
  },
];
